name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Jekyll site
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/srv/jekyll \
            -v ${{ github.workspace }}/vendor/bundle:/usr/local/bundle \
            jekyll/jekyll:4 \
            jekyll build

      - name: Deploy site to GitHub Pages
        run: |
          git config --global user.name "${{ secrets.GITHUB_ACTOR }}"
          git config --global user.email "${{ secrets.GITHUB_ACTOR }}@users.noreply.github.com"
          git add -A
          git commit -m "Deploy site"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
