name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Jekyll site
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/srv/jekyll \
            -v ${{ github.workspace }}/vendor/bundle:/usr/local/bundle \
            jekyll/jekyll:4 \
            jekyll build

      - name: Deploy to GitHub Pages
        if: success()
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

          # Initialize a new git repository in the _site directory
          cd _site
          git init
          git add .
          git commit -m "Deploy Jekyll site"

          # Force push to the gh-pages branch
          git push --force "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" main:gh-pages

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
